### ISSUE TITLE
Not show any Dates

### ISSUE THREAD

**Issue by dhruvvarde** [JoeCiou/JKCalendar#10]
Not shown any dates of Month in My new device 7+
Plz tell me what i do ?
![image1](https://user-images.githubusercontent.com/6779847/42490283-193514ca-842d-11e8-9c53-eee0a2fbfb82.png)

**Comment by JoeCiou** [comment]
Did you given height or constraint for JKCalendar?
You can refer example to use.

**Comment by dhruvvarde** [comment]
I got the issue, and solve it !!
You set static timezone in JKDay class, so i removed it.

**Comment by JoeCiou** [comment]
Did you use date of JKDay?
I have changed the date permissions of JKDay from public to internal in the latest version (1.0.4). If you want get date, I suggest use JKDay's year, month and day to convert. thx.

**Comment by dhruvvarde** [comment]
No issue is that, you set static timezone "GMT-0" in JKDay class,
You can check with other timezone eg.Newyork

![screen shot 2018-07-13 at 1 22 40 pm](https://user-images.githubusercontent.com/6779847/42679569-0d39f0e4-86a0-11e8-80cd-ec8f6ab1a47d.png)

**Comment by JoeCiou** [comment]
Thx. Is my wrong. I fixed.
