### ISSUE TITLE
Didselect delegate method not called

### ISSUE THREAD

**Issue by sanjukta-navsoft** [JoeCiou/JKCalendar#14]
I use JKCalendarTableView.  set the delegate. But the tableview delegate method didSelectRowAt method not called.....Please please help me out to solve this issue.

**Comment by unco182** [comment]
I have the same issue with my project.

To verify I tried to download and build the example project, but the didSelect method was not called. 
Any idea or fix coming soon ?

**Comment by hadiidbouk** [comment]
Same

**Comment by hadiidbouk** [comment]
I removed the `_delegate` from `JKCalendarTableView` and I use the `delegate` instead and now it works fine.

**Comment by ghazi256** [comment]
use the delegate how? Delegate it to calling class or the same class JKCalendarTableView

**Comment by ghazi256** [comment]
it assigns the delegate to _delegate. With _delegate gone what do u do with that statement

`override open var delegate: UITableViewDelegate?{
        set{
            callingClassDelegate = newValue
        }
        get{
            return callingClassDelegate
        }
    }`

**Comment by ghazi256** [comment]
I removed `override open var delegate: UITableViewDelegate?{ set{ callingClassDelegate = newValue } get{ return callingClassDelegate } }`

and  it is working fine now.

**Comment by JoeCiou** [comment]
I fix this. You can give `nativeDelegate` to use UITableView delegate function now.
