### ISSUE TITLE
Compatibility with SDK iOS 12.1

### ISSUE THREAD

**Issue by ikki08** [JoeCiou/JKCalendar#17]
I run my app with JKCalendar v1.1.0 in Xcode 10.1 then I got 3 error.

- 'common' has been renamed to 'RunLoopMode.commonModes'
- 'orientationDidChangeNotification' has been renamed to 'NSNotification.Name.UIDeviceOrientationDidChange'
- 'orientationDidChangeNotification' has been renamed to 'NSNotification.Name.UIDeviceOrientationDidChange'

Could you fix it as soon as possible?

**Comment by JoeCiou** [comment]
There are correct in Swift4.2
