### ISSUE TITLE
when loading scrollview based, everything gets stuck

### ISSUE THREAD

**Issue by galblank** [JoeCiou/JKCalendar#4]
when loading scrollview based, everything gets stuck
`calendarScrollView = JKCalendarScrollView(frame: self.view.frame)
        view |+| calendarScrollView!
        calendarScrollView!.m_edges |=| view
        calendarScrollView!.calendar.delegate = self
        calendarScrollView!.calendar.dataSource = self
//        calendarScrollView!.calendar.textColor = UIColor(red: 60/255,
//                                                        green: 60/255,
//                                                        blue: 60/255,
//                                                        alpha: 1)
        calendarScrollView!.calendar.backgroundColor = UIColor.white
        calendarScrollView!.calendar.focusWeek = JKCalendar.calendar.component(.weekOfMonth, from: selectDay.date) - 1
        calendarScrollView!.calendar.isInitializationCollapsed = true`

**Comment by JoeCiou** [comment]
If you say scrollview can't scroll. You should set content size for it.
`calendarScrollView.contentSize = CGSize(width: 0, height: 600)`
