### ISSUE TITLE
JKCalendarScrollView issues with month change

### ISSUE THREAD

**Issue by IsuruRanasinghe** [JoeCiou/JKCalendar#5]
Hi,

First of all this is a great library and thanks for that. 
I've used JKScrollview in my app and it works fine until expand and collapse happen.

When expand or collapse happen, calendar view month change is not changing (actually previous ad next functions triggers).

I've checked why is this happening and it seems like index issue. Could you please assists me on this issue how to resolve it.

Regards,
Isuru

**Comment by JoeCiou** [comment]
Hi, 

Thank you for your praise!
Because I can't re-generate this issue, please provide your code and more details.
