### ISSUE TITLE
JKDay convert to Date with wrong Date value

### ISSUE THREAD

**Issue by ikki08** [JoeCiou/JKCalendar#8]
JKDay always give us Date with GMT+0 value even if I use it in GMT+7. So when I try to compare between today date that I got from system and the date that converted from JKDay it will always give us a false except we are in GMT+0 timezone.

**Comment by JoeCiou** [comment]
After I have reviewed it, I will remove the "public" of date in the later version, because JKDay only represents the date without time. If you need to convert the Date from JKDay, please use JKDay's year, month, and day to generate it yourself, thank you!
